spring:
  application:
    name: graph
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:mydatabase}
    username: ${POSTGRES_USERNAME:myuser}
    password: ${POSTGRES_PASSWORD:secret}
  jpa:
    show-sql: true